### PR TITLE
Right align the footer

### LINKED ISSUE #128: right align text in footer
image

'Quick links' should be right aligned

### PR DESCRIPTION
**Pull request by AKSHATNEMA**
# Right Align Footer

## Description

This PR includes the changes to right-align the Quick Links in the footer section and updated the package-lock.json file so that the latest versions of dependencies and node packages get installed.

Fixes #128 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My contribution follows the style guidelines of this project
- [x] I have performed a self-review of my own contribution
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

## Preview/Screenshots
**Desktop view**
image

**Mobile View**
image

### CODE REVIEW

**Comment by AKSHATNEMA** [comment]
@shikha-16 @nehakalbande, kindly merge this pull request under Hacktoberfest 2021.

**Comment by shikha-16** [comment]
Hi @AKSHATNEMA in the desktop view, could the icons be shifted a little more to the left (or text be shifted to the right more) so that the text is perfectly above the 4 icons below. Thanks

**Comment by AKSHATNEMA** [comment]
@shikha-16 ok, will try to make a better look for this and will give you preview in Discord DM. Please be active on Discord.

**Comment by AKSHATNEMA** [comment]
@shikha-16 have a look at this.
Desktop view
image

Mobile view
image

**Comment by shikha-16** [comment]
> @shikha-16 have a look at this. Desktop view image
> 
> Mobile view image
> 
> is it now ok?

yes its fine! 
merging now

**Pull request merged**
