### PR TITLE
Add Contributing page

### PR DESCRIPTION
**Pull request by milenagd**
# Pull Request Template

Fixes # (issue)
#57 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My contribution follows the style guidelines of this project
- [ ] I have performed a self-review of my own contribution
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings

image
image
image

### CODE REVIEW

**Comment by umang-sinha** [comment]
@milenagd it would be great if you could attach a screenshot or a short video displaying how the page looks

**Comment by shikha-16** [comment]
> @milenagd it would be great if you could attach a screenshot or a short video displaying how the page looks

@milenagd if you do this like in #56 we will be able to understand it better and merge it right away

**Comment by milenagd** [comment]
I added the pictures

**Comment by umang-sinha** [comment]
> I added the pictures

this is for the smaller screens. What about the desktop version?

**Comment by milenagd** [comment]
image
image

**Comment by milenagd** [comment]
You can also checkout to my branch, in order to see the changes

**Comment by umang-sinha** [comment]
great job @milenagd Thanks for contributing. Please go through other issues if you would like to contribute more.

**Pull request merged**
