### PR TITLE
added scroll to top button

### PR DESCRIPTION
**Pull request by PDahiya123**
# Pull Request Template

## Description

Added scroll to top button

Fixes # 117

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My contribution follows the style guidelines of this project
- [x] I have performed a self-review of my own contribution
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by nehakalbande** [comment]
Hi @PDahiya123 Can you place the scrollbutton in the bottom right corner!

**Comment by nehakalbande** [comment]
@PDahiya123 Its not mobile responsive, Please have a look over it!

**Comment by PDahiya123** [comment]
@nehakalbande can you please check it now.

**Review by nehakalbande — COMMENTED** [review]
Hi @PDahiya123 , sorry there are some issues while accepting the PR.. Please make a new PR by fetching the updated changes in the repo

**Comment by shikha-16** [comment]
@nehakalbande there are no conflicts for this PR though

**Review by nehakalbande — APPROVED** [review]
Merging #122 🎉

**Pull request merged**
