### PR TITLE
Dark Mode

### PR DESCRIPTION
**Pull request by Simranjakhodia**
# Pull Request Template

## Description
Dark Mode Feature & updated fav-icons in navbar

Fixes # 123

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My contribution follows the style guidelines of this project
- [ ] I have performed a self-review of my own contribution
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by Simranjakhodia** [comment]
Please review and accept my pull request 
Fixes #123

**Comment by Simranjakhodia** [comment]
@shikha-16  I've made commits according to all the points mentioned 
 a) Changed the color to Dark Gray where it was blue making txt white
 b) Positioning of  moon icon
 c) Spacing btw the fav icon and text.
Screenshot (325)
Screenshot (327)


Hoping to get this merged.
Thankyou.

**Review by nehakalbande — APPROVED** [review]
Merging #124 Great work 🎉

**Comment by shikha-16** [comment]
Hi @Simranjakhodia we aren't able to merge this PR Because the branch has some conflicts. Please resolve them. 
Also I meant that the colour of the text should be white, not the background. Please change that as well.

**Comment by nehakalbande** [comment]
The conflicts are in package-lock.json file and Header file

**Review by shikha-16 — APPROVED** [review]

**Review by nehakalbande — APPROVED** [review]

**Comment by shikha-16** [comment]
@Simranjakhodia Please make a new PR after pulling the repo onto your local machine again, since there seems to be a problem with this one. Also I meant that the colour of the text should be white, not the background. Please change that as well.

**Comment by Simranjakhodia** [comment]
@shikha-16  The white background which you want to be modified , for that I'll have to go through the entire components folder as there are multiple pages linked and changes need to be made in all.  This will require some more time.  Currently, will get these conflicts resolved to get this PR merged.

**Review by nehakalbande — COMMENTED** [review]
Hi @Simranjakhodia  , sorry there are some issues while accepting the PR.. Please make a new PR by fetching the updated changes in the repo

**Comment by Simranjakhodia** [comment]
@nehakalbande  I cant make another PR with  master branch on Simranjakhodia/Women-in-Technology.

**Review by nehakalbande — APPROVED** [review]

**Review by nehakalbande — APPROVED** [review]

**Comment by shikha-16** [comment]
> @shikha-16 The white background which you want to be modified , for that I'll have to go through the entire components folder as there are multiple pages linked and changes need to be made in all. This will require some more time. Currently, will get these conflicts resolved to get this PR merged.

Hi @Simranjakhodia I hope you're working on this.

**Pull request closed without merging**
