### PR TITLE
Added previous scholars experience.

### PR DESCRIPTION
**Pull request by SudeepaNoble**
In the scholarships section, added the articles of previous scholars.

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My contribution follows the style guidelines of this project
- [ ] I have performed a self-review of my own contribution
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by shikha-16** [comment]
Hi! I would like for the additions to be italicized and on the next line, with proper punctuation as well.

**Comment by SudeepaNoble** [comment]
> Hi! I would like for the additions to be italicized and on the next line, with proper punctuation as well.

Yeah, sure. Check now.

**Review by SudeepaNoble — COMMENTED** [review]
Additions are now italicized.

**Comment by shikha-16** [comment]
good work!

**Pull request merged**
