### PR TITLE
links change according to theme color

### PR DESCRIPTION
**Pull request by sungod12**
# Pull Request Template

## Description

-Changed link colors to black and white in order to be visible in light and dark mode as per requirements.

Fixes # 142

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My contribution follows the style guidelines of this project
- [x] I have performed a self-review of my own contribution
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by sungod12** [comment]
Please review and let me know @nehakalbande.

**Comment by nehakalbande** [comment]
> Please review and let me know @nehakalbande.

There is conflict in event.js file. Please check

**Comment by sungod12** [comment]
check now.

**Comment by shikha-16** [comment]
Okay, merging

**Comment by sungod12** [comment]
Thanks @shikha-16 .Let me know if any issue occurs after merging.

**Comment by nehakalbande** [comment]
Screenshot (71)

**Comment by shikha-16** [comment]
@sungod12 There is a problem with your tags, please check all these issues before creating a PR, had to revert it.

**Comment by shikha-16** [comment]
There was some error after we accepted your PR, please check if it's working properly and only then create a new PR @sungod12 
Marking this one invalid

**Comment by sungod12** [comment]
okay.

**Comment by shikha-16** [comment]
@sungod12 
these changes ka PR again, after pulling the repo to your local machine, and checking for errors before making the PR

**Comment by sungod12** [comment]
okay, check for error by checking for new code and then create new pr for same right?

**Pull request merged**
