### PR TITLE
Remade Cards and Study Resource Page

### LINKED ISSUE #139: Remake as cards
Remake all the entries in 'Articles & Blogs' and 'Github Repositories to Star' and 'Infographics' as cards in 3 different sections of the Other Resources page. (And delete the existing things)
Screenshot from 2021-09-03 00-12-39
Screenshot from 2021-09-03 00-15-14
Screenshot from 2021-09-03 00-15-33

### PR DESCRIPTION
**Pull request by madhhuurrii**
# Pull Request Template

## Description

1. Created Study Resource Page and Remade cards in the page.

Fixes #139

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My contribution follows the style guidelines of this project
- [x] I have performed a self-review of my own contribution
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

studyresource

### CODE REVIEW

**Comment by shikha-16** [comment]
Hi @madhhuurrii, just see these conflicting files and resolve the conflicts please. We merged another PR so it had to happen.

**Comment by madhhuurrii** [comment]
> Hi @madhhuurrii, just see these conflicting files and resolve the conflicts please. We merged another PR so it had to happen.

Yes will do!

**Comment by shikha-16** [comment]
@madhhuurrii so sorry for the inconvenience, please look at 1 more conflict, and i will merge yours next!

**Comment by madhhuurrii** [comment]
Hii @shikha-16 , I have finished editing all the changes! Please review the PR :)
The Final page now looks like this. 
studyresource final

**Comment by madhhuurrii** [comment]
Hii @shikha-16 , I have made the required changes, Please look into it
studyresource

**Comment by madhhuurrii** [comment]
> Hi @madhhuurrii Footer icons doesnt seem responsive in the ss. Please have a look over it.
I didn't  tried modifying the footer components, I don't what is causing it, will look into it!

**Pull request merged**
