### PR TITLE
#142 Fixed links which where were not properly visible in dark mode

### PR DESCRIPTION
**Pull request by sungod12**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
-Fixed links which where were not visible in dark mode by setting background color to lighter version of black.
-Changed link color in other pages which were not properly visible due to dark colored background.
-Justified text in scholarship component.

Fixes # 142

## Type of change

Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My contribution follows the style guidelines of this project
- [x] I have performed a self-review of my own contribution
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by nehakalbande** [comment]
Files are Conflicting, Please have a look over it

**Comment by sungod12** [comment]
I have removed most of conflicts.

**Comment by nehakalbande** [comment]
Conflicting files
website/src/components/Footer/Footer.js
website/src/components/Header/Header.js
website/src/components/Inspirational/Inspirational.js
website/src/components/Resources/resourcesComponent.js
website/src/components/Scholarships/ScholarshipComponent.js

**Comment by nehakalbande** [comment]
Please remove the ss of your changes from the documents folder and send them here.

**Comment by sungod12** [comment]
> Please remove the ss of your changes from the documents folder and send them here.

okay
-Before changing background color
before changing background color

- After changing background color
after changing background color

-Before justifying text 
before justifying text

-After justifying text
after justifying text

**Comment by nehakalbande** [comment]
> > Please remove the ss of your changes from the documents folder and send them here.
> 
> okay -Before changing background color before changing background color
> 
> * After changing background color
>   after changing background color
> 
> -Before justifying text before justifying text
> 
> -After justifying text after justifying text

Can you change the name and links of the scholarship any other color, Black doesn't seem good

**Comment by sungod12** [comment]
> > > Please remove the ss of your changes from the documents folder and send them here.
> > 
> > 
> > okay -Before changing background color before changing background color
> > 
> > * After changing background color
> >   after changing background color
> > 
> > -Before justifying text before justifying text
> > -After justifying text after justifying text
> 
> Can you change the name and links of the scholarship any other color, Black doesn't seem good

You want me change the name and color of the links.

**Comment by nehakalbande** [comment]
> > > > Please remove the ss of your changes from the documents folder and send them here.
> > > 
> > > 
> > > okay -Before changing background color before changing background color
> > > 
> > > * After changing background color
> > >   after changing background color
> > > 
> > > -Before justifying text before justifying text
> > > -After justifying text after justifying text
> > 
> > 
> > Can you change the name and links of the scholarship any other color, Black doesn't seem good
> 
> You want me to change the name as well as color of the links?

Yes

**Comment by sungod12** [comment]
Well the name seems good, I can change the color. Is that okay?

> > > > > Please remove the ss of your changes from the documents folder and send them here.
> > > > 
> > > > 
> > > > okay -Before changing background color before changing background color
> > > > 
> > > > * After changing background color
> > > >   after changing background color
> > > > 
> > > > -Before justifying text before justifying text
> > > > -After justifying text after justifying text
> > > 
> > > 
> > > Can you change the name and links of the scholarship any other color, Black doesn't seem good
> > 
> > 
> > You want me to change the name as well as color of the links?
> 
> Yes

Well the name seems good, I can change the color. Is that okay?

**Comment by sungod12** [comment]
Color in light mode.
image

Color in dark Mode
image

Is this color okay?

**Comment by shikha-16** [comment]
wait what is happening

**Comment by sungod12** [comment]
Hi @shikha-16 @nehakalbande ,I haven't yet commited the changed color.

**Comment by sungod12** [comment]
> Hi @shikha-16 @nehakalbande ,I haven't yet commited the changed color.

I was waiting for approval, hence didn't commit the change.

**Comment by shikha-16** [comment]
Yeah, sorry i merged by mistake. 
So 

> Color in light mode. image
> 
> Color in dark Mode image
> 
> Is this color okay?

Hey, can you change the 'Generation Google Scholarship' color to white bold in dark mode and keep it black bold in light mode? Underline the text if it links to anywhere.
Also, change the 'here' at the end of text as well.

**Comment by sungod12** [comment]
> Yeah, sorry i merged by mistake. So
> 
> > Color in light mode. image
> > Color in dark Mode image
> > Is this color okay?
> 
> Hey, can you change the 'Generation Google Scholarship' color to white bold in dark mode and keep it black bold in light mode? Underline the text if it links to anywhere. Also, change the 'here' at the end of text as well.

It was previously but @nehakalbande told me to change color as black doesn't look good.

**Comment by sungod12** [comment]
> > Yeah, sorry i merged by mistake. So
> > > Color in light mode. image
> > > Color in dark Mode image
> > > Is this color okay?
> > 
> > 
> > Hey, can you change the 'Generation Google Scholarship' color to white bold in dark mode and keep it black bold in light mode? Underline the text if it links to anywhere. Also, change the 'here' at the end of text as well.
> 
> It was previously but @nehakalbande told me to change color as black doesn't look good.

Just decide among yourselves and let me know then, I will make changes accordingly. Also if possible, could you notify me on discord about the final decision instead of github.

**Comment by nehakalbande** [comment]
> > Yeah, sorry i merged by mistake. So
> > > Color in light mode. image
> > > Color in dark Mode image
> > > Is this color okay?
> > 
> > 
> > Hey, can you change the 'Generation Google Scholarship' color to white bold in dark mode and keep it black bold in light mode? Underline the text if it links to anywhere. Also, change the 'here' at the end of text as well.
> 
> It was previously but @nehakalbande told me to change color as black doesn't look good.

Told you for dark mode... Not for light mode

**Comment by nehakalbande** [comment]
> > Color in light mode. image
> > Color in dark Mode image
> > Is this color okay?
> 
> Hey, can you change the 'Generation Google Scholarship' color to white bold in dark mode and keep it black bold in light mode? Underline the text if it links to anywhere. Also, change the 'here' at the end of text as well.

@sungod12 Change it like this

**Comment by sungod12** [comment]
Thats it,right?

**Comment by nehakalbande** [comment]
> Thats it,right?

Yes, But do the same changes in other files as well organisations and other..

**Comment by sungod12** [comment]
> > Thats it,right?
> 
> Yes, But do the same changes in other files as well organisations and other..

you mean other links in other pages.okay.

**Comment by sungod12** [comment]
> > > Thats it,right?
> > 
> > Yes, But do the same changes in other files as well organisations and other..
> 
> you mean other links in other pages.okay.

is this possible to add it as new issue because this was for particular page i e,organization and now link color have to be changed for each and every page.

**Comment by shikha-16** [comment]
> > > > Thats it,right?
> > > 
> > > 
> > > Yes, But do the same changes in other files as well organisations and other..
> > 
> > 
> > you mean other links in other pages.okay.
> 
> is this possible to add it as new issue because this was for particular page i.e, organization and now link color have to be changed for each and every page.
> 
> also as two of my commits got merged as one this could act as replacement for it.
> 
> update:I have changed the color using use effect hook and setinterval ,but there is slight flashing due to setinterval.If that is okay,i can merge or anybody wants to help they are free to do so.

@nehakalbande

**Comment by nehakalbande** [comment]
> > > > Thats it,right?
> > > 
> > > 
> > > Yes, But do the same changes in other files as well organisations and other..
> > 
> > 
> > you mean other links in other pages.okay.
> 
> is this possible to add it as new issue because this was for particular page i.e, organization and now link color have to be changed for each and every page.
> 
> also as two of my commits got merged as one this could act as replacement for it.
> 
> update:I have changed the color using use effect hook and setinterval ,but there is slight flashing due to setinterval.If that is okay,i can merge or anybody wants to help they are free to do so.

Can you send the ss of the set interval code and the color change in the website

**Comment by sungod12** [comment]
> the

sure.I will send the gif along with code and short explanation.

**Comment by sungod12** [comment]
sure.I will send the gif along with code and short explanation.

**Comment by sungod12** [comment]
> sure.I will send the gif along with code and short explanation.

```
//Used a state for storing theme and changing it dynamically
const [theme, setTheme] = useState("light");
  useEffect(() => {
    const interval = setInterval(() => {
      const temptheme = localStorage.getItem("theme"); //fetches the theme
      setTheme(temptheme); //sets the theme
      const names = [                           //array which contains the id of tags which needs to be changed on switching theme
        "scholarship-name-1",
        "scholarship-name-2",
        "scholarship-name-3",
        "scholarship-name-4",
        "scholarship-name-5",
        "scholarship-name-6",
        "scholarship-name-7",
      ];
      if (theme === "dark") {                          /*checks the theme and if it is dark add class "dark" to the classList thereby changing
        names.forEach((val) => {                         color of links*/
          document.getElementById(`${val}`).classList.add("dark");
          document.getElementById(`${val}`).classList.remove("light");
        });
      } else {
        names.forEach((val) => {
          document.getElementById(`${val}`).classList.add("light");
          document.getElementById(`${val}`).classList.remove("dark");
        });
      }
      return;
    }, 500);                  //checks for theme change every 500ms
  }, [theme]);                  //runs on theme state change.
```

**Comment by sungod12** [comment]
This is what is occuring
IF_2Tn

**Comment by nehakalbande** [comment]
> > sure.I will send the gif along with code and short explanation.
> 
> ```
> //Used a state for storing theme and changing it dynamically
> const [theme, setTheme] = useState("light");
>   useEffect(() => {
>     const interval = setInterval(() => {
>       const temptheme = localStorage.getItem("theme"); //fetches the theme
>       setTheme(temptheme); //sets the theme
>       const names = [                           //array which contains the id of tags which needs to be changed on switching theme
>         "scholarship-name-1",
>         "scholarship-name-2",
>         "scholarship-name-3",
>         "scholarship-name-4",
>         "scholarship-name-5",
>         "scholarship-name-6",
>         "scholarship-name-7",
>       ];
>       if (theme === "dark") {                          /*checks the theme and if it is dark add class "dark" to the classList thereby changing
>         names.forEach((val) => {                         color of links*/
>           document.getElementById(`${val}`).classList.add("dark");
>           document.getElementById(`${val}`).classList.remove("light");
>         });
>       } else {
>         names.forEach((val) => {
>           document.getElementById(`${val}`).classList.add("light");
>           document.getElementById(`${val}`).classList.remove("dark");
>         });
>       }
>       return;
>     }, 500);                  //checks for theme change every 500ms
>   }, [theme]);                  //runs on theme state change.
> ```

Please use setTimeout to resolve this issue

**Comment by sungod12** [comment]
> > > sure.I will send the gif along with code and short explanation.
> > 
> > 
> > ```
> > //Used a state for storing theme and changing it dynamically
> > const [theme, setTheme] = useState("light");
> >   useEffect(() => {
> >     const interval = setInterval(() => {
> >       const temptheme = localStorage.getItem("theme"); //fetches the theme
> >       setTheme(temptheme); //sets the theme
> >       const names = [                           //array which contains the id of tags which needs to be changed on switching theme
> >         "scholarship-name-1",
> >         "scholarship-name-2",
> >         "scholarship-name-3",
> >         "scholarship-name-4",
> >         "scholarship-name-5",
> >         "scholarship-name-6",
> >         "scholarship-name-7",
> >       ];
> >       if (theme === "dark") {                          /*checks the theme and if it is dark add class "dark" to the classList thereby changing
> >         names.forEach((val) => {                         color of links*/
> >           document.getElementById(`${val}`).classList.add("dark");
> >           document.getElementById(`${val}`).classList.remove("light");
> >         });
> >       } else {
> >         names.forEach((val) => {
> >           document.getElementById(`${val}`).classList.add("light");
> >           document.getElementById(`${val}`).classList.remove("dark");
> >         });
> >       }
> >       return;
> >     }, 500);                  //checks for theme change every 500ms
> >   }, [theme]);                  //runs on theme state change.
> > ```
> 
> Please use setTimeout to resolve this issue

I had used setTimeout previously but it worked for first time and then didnt work,I will try again.

**Comment by sungod12** [comment]
ahhh i solved the issue. Damn it, it was due to just one css property  and played around with it and got the solution.

**Comment by sungod12** [comment]
Light Mode
image

Dark Mode
image

**Comment by sungod12** [comment]
Should I go with this change?. Please review @nehakalbande @shikha-16

**Comment by nehakalbande** [comment]
@sungod12 Great
Please make a PR, So that we can review the code

**Comment by sungod12** [comment]
okay. I am making changes only in scholarship page, then make a pull request and then do rest of pages in order to review first or should I change it in other pages accordingly and then make a pull request?.

**Comment by nehakalbande** [comment]
> okay. I am making changes only in scholarship page, then make a pull request, in order to review and then do rest of pages or should I change it in other pages accordingly and then make a pull request?.

Make the changes in other pages as well,then make a PR

**Comment by sungod12** [comment]
okay.

**Comment by sungod12** [comment]
Changed pages-

Dark Mode-
Scholarships
image

Light Mode-
Scholarships
image

Dark Mode-
Events/Programs
image

Light Mode-
Events/Programs
image

Dark Mode-
Inspirations
image

Light Mode-
Inspirations
image

Dark Mode-
Guidelines
image

Light Mode-
Guidelines
image

**Comment by nehakalbande** [comment]
> Changed pages-
> 
> Dark Mode- Scholarships image
> 
> Light Mode- Scholarships image
> 
> Dark Mode- Events/Programs image
> 
> Light Mode- Events/Programs image
> 
> Dark Mode- Inspirations image
> 
> Light Mode- Inspirations image
> 
> Dark Mode- Guidelines image
> 
> Light Mode- Guidelines image

Please remove the changes done in Events/Programs Page. Some other changes has been done on that page

**Comment by sungod12** [comment]
i am resolving the conflicts.

**Comment by sungod12** [comment]
okay. You should have told me previously.

**Pull request merged**
