### PR TITLE
Repo of the month

### LINKED ISSUE #45: Repo of the month
Want a repo-of-the-month section where you link a really cool repo that visitors can explore. I would want this both on the repo and on discord. You have to change it every month. I feel like it would keep the repo and discord community active and engaging.

Whoever wants to contribute HAS to comment here AND join the [Discord](https://discord.com/invite/xvzbAXk) server to communicate.  Please also go through [Contributing.md](https://github.com/shikha-16/Women-in-Technology/blob/master/Contributing.md) and follow ALL instructions when making a PR, otherwise, it will be rejected.

### PR DESCRIPTION
**Pull request by peppermint-juli**
## Description

Added the November 2020 version of the Repository of the month section in the README.md of this repo.

Fixes #45

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My contribution follows the style guidelines of this project
- [x] I have performed a self-review of my own contribution
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by shikha-16** [comment]
Hi @peppermint-juli ! Thank you for following up :)
So whatever repos you are featuring in repo of the month, please do add them in the 'Other Helpful Repositories' section as well, so people can refer to them in the future.
Also please make an announcement on the discord server about the new repo of the month! It will keep the community active and engaged. I'll give you announcement permissions. 
Please do acknowledge this message.

**Comment by peppermint-juli** [comment]
@shikha-16 got it! I'll make sure to have these in mind!

**Comment by shikha-16** [comment]
> @shikha-16 got it! I'll make sure to have these in mind! 

Are you on the discord server? What's your user?

**Comment by peppermint-juli** [comment]
I am! Username is julianajaime

**Pull request merged**
