### PR TITLE
updated footer

### PR DESCRIPTION
**Pull request by qwerty-rgb**
# Pull Request Template

## Description

Created a new footer and image file in react

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My contribution follows the style guidelines of this project
- [ ] I have performed a self-review of my own contribution
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by qwerty-rgb** [comment]
added new footer element
please check

**Comment by umang-sinha** [comment]
@qwerty-rgb I am unable to run this project in my browser for some reason. Can you run it on your local machine and attach a screenshot of the footer component that you built?

**Comment by qwerty-rgb** [comment]
actually i have made on codesandbox which is an online ide as my machine is a little old and it cannot import so many packages
so please refer to https://codesandbox.io/docs/importing
I hope you understand

**Comment by umang-sinha** [comment]
Hey! @qwerty-rgb I checked it on the sandbox and everything looks fine to me. But there's just one small thing that you missed. The "Back to the top" thing should be clickable and should take the user to the top of the page when clicked. 
Also, just copy paste your code into a new file called Footer.jsx under the components directory and then render it so that the component can be easily reused for other pages.

**Comment by qwerty-rgb** [comment]
The "back to top" will work if we apply the id of the navbar which needs to be set according to the navbar id. Now because i dont have the full code then anybody can do it. In the code itself i have added the solution then whenever someone will take it is easy for them. And also Footer.jsx is already present in the components section. Kindly check :)

**Comment by umang-sinha** [comment]
oops! My bad. I guess I missed that. Everything looks fine to me. I am merging this. Thanks for contributing!

**Comment by umang-sinha** [comment]
@qwerty-rgb  I guess you made the pull request into the wrong branch. Please make sure you make the commit to the 'website' branch and not the 'master' branch

**Comment by shikha-16** [comment]
@qwerty-rgb please see here

**Pull request merged**
