### PR TITLE
#131 changed links to open in new tab

### PR DESCRIPTION
**Pull request by sungod12**
# Pull Request Template

## Description

Fixes #issue131

## Type of changes

- [x] Bug fix (non-breaking change which fixes an issue)
      -[ ] Removed warnings occuring due to adding target="_blank".
      -[ ] Aligned the dark mode icon to center and changed the color on hover to black.
      -[ ] Solved ValidDOMNesting error due to "a being descendant of p" and "h5 being descendant of p"
      -[ ] Added keys where map function is used for rendering components.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
      -[ ] The women in tech logo in inspirations page is aligned to left even though I didn't change the CSS.

## Checklist:

- [x] I have performed a self-review of my own contribution
- [x] My contribution follows the style guidelines of this project
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by nehakalbande — COMMENTED** [review]
Hi @sungod12 . Please change the links given in this page to open in new tab. If its already done let us know. 🙂
Screenshot (60)

**Comment by sungod12** [comment]
Hi @nehakalbande .I have also changed the above links to open in new tab.

**Comment by shikha-16** [comment]
> Hi @nehakalbande .I have also changed the above links to open in new tab.

hi, is this a general PR or do you want this to count towards hacktoberfest?

**Comment by sungod12** [comment]
Thanks for asking. I would like count it towards hacktoberfest.

**Comment by shikha-16** [comment]
HI @sungod12 can you please update this to not have conflicts. We just updated the repo actually, sorry for the inconvenience!

**Comment by sungod12** [comment]
Hi @shikha-16 @nehakalbande  ,made the changes, review them and let me know if there are any issues. Thanks.

**Comment by sungod12** [comment]
Sorry to disturb @shikha-16 @nehakalbande ,but this request is not shown in my hacktoberfest pull requests. Is it due to pull request being closed?

**Comment by nehakalbande** [comment]
> Sorry to disturb @shikha-16 @nehakalbande ,but this request is not shown in my hacktoberfest pull requests. Is it due to pull request being closed?

Please refresh the hacktoberfest site, it do takes time to get visible

**Comment by sungod12** [comment]
> > Sorry to disturb @shikha-16 @nehakalbande ,but this request is not shown in my hacktoberfest pull requests. Is it due to pull request being closed?
> 
> Please refresh the hacktoberfest site, it do takes time to get visible

okay.Thanks

**Pull request merged**
