### PR TITLE
Responsiveness improved

### PR DESCRIPTION
**Pull request by Sonakshi1901**
I have fixed the responsiveness of the homepage and the contribution page as asked.
Screenshots are attached. Do let me know the required changes, if any.

wit1
wit2
wit3

### CODE REVIEW

**Review by nehakalbande — COMMENTED** [review]
Hey @Sonakshi1901 Please make this corrections:
1. Testinomial component more responsive. Carousel-text css is not there! 
2. In Carousel Component, if class is getting changed into carousel-slide then carousel are not working.

**Comment by Sonakshi1901** [comment]
When class is changed to carousel-slide, then the carousel is working. There is no issue there

**Comment by Sonakshi1901** [comment]
Please check it and let me know if it's alright.

**Review by nehakalbande — APPROVED** [review]
Great work 🎉

**Pull request merged**
