### PR TITLE
fixes dak theme in community pag

### PR DESCRIPTION
**Pull request by maryanamorato**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

https://github.com/shikha-16/Women-in-Technology/issues/165

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x ] My contribution follows the style guidelines of this project
- [x ] I have performed a self-review of my own contribution
- [x ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by maryanamorato** [comment]
@nehakalbande hi!
even in the light theme these lines are appearing. Ill open 2 prs ok? Can you merge this first?

**Comment by maryanamorato** [comment]
by the way, are you asking me to remove the lines only in dark mode? @nehakalbande

**Comment by nehakalbande** [comment]
> @nehakalbande hi! even in the light theme these lines are appearing. Ill open 2 prs ok? Can you merge this first?

Hi @maryanamorato , Remove the lines both from light and dark mode. You can commit the changes in this PR too :)

**Comment by maryanamorato** [comment]
Im trying to complete the hacktober fest challenge. hehe
Lets help each other, if aint a problem to you

**Comment by nehakalbande** [comment]
> @nehakalbande Im trying to complete the hacktober fest challenge. hehe Lets help each other, if aint a problem to you

Okay! I'll merge it, since today is the last day of hacktoberfest :) 
Please add an issue of removing the lines and do comment over it, will assign it to you

**Review by nehakalbande — APPROVED** [review]
PR Accepted #193

**Comment by maryanamorato** [comment]
Ok! Ill do it right now. And for my 4th PR, ill add one more event in the list. Hope I was useful to the project.

**Pull request merged**
