### PR TITLE
Events Page Added

### LINKED ISSUE #91: Events/Programs section in website
image

I want a page in the website in the 'Resources' section for these as well. Please go through the code and comment here if you are willing to contribute. Thanks! :)
Website - https://women-in-technology-wit.web.app/

### PR DESCRIPTION
**Pull request by rishkwal**
# Pull Request Template

## Description

Added an Events/Programs page to the main website

Fixes #91 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My contribution follows the style guidelines of this project
- [x] I have performed a self-review of my own contribution
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by nehakalbande — COMMENTED** [review]
Provide links for events as well..

**Comment by shikha-16** [comment]
@rishkwal Hey can you please update the PR after adding links as well

**Comment by rishkwal** [comment]
> @rishkwal Hey can you please update the PR after adding links as well

Hey, I have updated the PR with the links I found. I wasn't able to find three of them though.

**Review by nehakalbande — COMMENTED** [review]
Hey @rishkwal Please gives some other names to classNames.
These classNames are already been given. They are conflicting.
And for the "headings" or "a" tag please give them className and then do the css part.

**Comment by rishkwal** [comment]
> Hey @rishkwal Please give some other names to classNames.
> These classNames are already been given. They are conflicting.
> And for the "headings" or "a" tag please give them className and then do the css part.

Are you talking about the className "list"?

**Review by nehakalbande — COMMENTED** [review]
list, h1, li, a
Please give them some classname and then do the css part..

**Comment by rishkwal** [comment]
> list, h1, li, a
> Please give them some classname and then do the css part..

Done, can you check if it is fine?

**Review by nehakalbande — COMMENTED** [review]
Please Change the word "class" into "className" in event.js

**Comment by rishkwal** [comment]
> Please Change the word "class" into "className" in event.js

My bad. Any other changes?

**Review by nehakalbande — APPROVED** [review]
Merging #98 @rishkwal Great work🎉

**Pull request merged**
