### PR TITLE
Remove majority of warnings occurring due to unused imports 

### PR DESCRIPTION
**Pull request by sungod12**
# Pull Request Template

## Description
-Remove majority of warnings occurring due to unused imports and other such basic warnings like "add rel="noreferrer" where
target="_blank" tags are used". 
-The files which were removed have been saved in **documents/changes** folder under UnusedImports.txt file along with the path of files in which they were imported.

Fixes # issue 149

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My contribution follows the style guidelines of this project
- [x] I have performed a self-review of my own contribution
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by sungod12** [comment]
Hi @nehakalbande ,I have opened pull request for issue #149 which was not possible, but on akshat's advice, I created new branch from the commit and was successfully able to open the issue. So please have a look through it, and let me know if anything is required.

**Comment by shikha-16** [comment]
HI @sungod12 same thing here, please update, thanks!

**Comment by sungod12** [comment]
I have resolved the issue. Please review the changes and if there any still issue, let me know.

**Comment by nehakalbande** [comment]
Can you please send the ss of your changes on the website?

**Comment by sungod12** [comment]
> Can you please send the ss of your changes on the website?

I have included them in document/changes folder.

**Comment by nehakalbande** [comment]
Files are conflicting now, due to the changes in website/src/components/Community/Contributors/ContributorsComponent.js
Have a look over it

**Comment by nehakalbande** [comment]
> > Can you please send the ss of your changes on the website?
> 
> I have included them in document/changes folder.

What did you change in this PR?

**Comment by sungod12** [comment]
Hi @nehakalbande , I have resolved most of conflicts and if I did it right, there should not be any more conflicts. If there are I will resolve them

**Comment by sungod12** [comment]
> > > Can you please send the ss of your changes on the website?
> > 
> > 
> > I have included them in document/changes folder.
> 
> What did you change in this PR?

I removed all the files where were imported but not used and saved them as UnusedImports.txt file under documents/changes folder.

**Comment by nehakalbande** [comment]
> > > > Can you please send the ss of your changes on the website?
> > > 
> > > 
> > > I have included them in document/changes folder.
> > 
> > 
> > What did you change in this PR?
> 
> I removed all the files where were imported but not used and saved them as UnusedImports.txt file under documents/changes folder.

Can only see one file change
Screenshot (65)
d

**Comment by nehakalbande** [comment]
This issue also got merged due to your Previous PR Acceptation, The UnusedImports.txt also been added

**Comment by sungod12** [comment]
> > > > > Can you please send the ss of your changes on the website?
> > > > 
> > > > 
> > > > I have included them in document/changes folder.
> > > 
> > > 
> > > What did you change in this PR?
> > 
> > 
> > I removed all the files where were imported but not used and saved them as UnusedImports.txt file under documents/changes folder.
> 
> Can only see one file change Screenshot (65) d



> This issue also got merged due to your Previous PR Acceptation, The UnusedImports.txt also been added

yes, two pull requests got commited to one.

**Comment by sungod12** [comment]
so could you please accept this commit or it will be counted as duplicate?

**Comment by nehakalbande** [comment]
> > > > > > Can you please send the ss of your changes on the website?
> > > > > 
> > > > > 
> > > > > I have included them in document/changes folder.
> > > > 
> > > > 
> > > > What did you change in this PR?
> > > 
> > > 
> > > I removed all the files where were imported but not used and saved them as UnusedImports.txt file under documents/changes folder.
> > 
> > 
> > Can only see one file change Screenshot (65) d
> 
> > This issue also got merged due to your Previous PR Acceptation, The UnusedImports.txt also been added
> 
> yes, two pull requests got commited to one.

Yes, Had told you to contribute one PR at a time. 
This issue usually arises

**Comment by nehakalbande** [comment]
Cant accept it now.

**Comment by nehakalbande** [comment]
> so could you please accept this commit or it will be counted as duplicate?

This PR will also not be recognized as a valuable PR to hacktoberfest reviewers too.

**Comment by sungod12** [comment]
> > so could you please accept this commit or it will be counted as duplicate?
> 
> This PR will also not be recognized as a valuable PR to hacktoberfest reviewers too.

okay, learnt from my mistakes.Thanks

**Comment by sungod12** [comment]
I will close it.

**Pull request closed without merging**
