### PR TITLE
Merge pull request(Cyber Security Infographic) #51 from shikha-16/master

### PR DESCRIPTION
**Pull request by wannabehacker007**
change

# Pull Request Template

## Description

This is the Infographic for Cyber Security:-
[Cyber Security_WiT.pdf](https://github.com/shikha-16/Women-in-Technology/files/5366018/Cyber.Security_WiT.pdf)
I have made sure to mention the Women In Technology Logo in it. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [1] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My contribution follows the style guidelines of this project
- [1] I have performed a self-review of my own contribution
- [ ] I have made corresponding changes to the documentation
- [1] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by shikha-16** [comment]
? where have you uploaded the infographic exactly?
I need you to fork the repo, and add it to documents -> infographics
then create a PR: https://github.com/shikha-16/Women-in-Technology/blob/master/Contributing.md

**Comment by wannabehacker007** [comment]
Sorry, for the trouble! I have done so, can you check out the PR I made again?

**Comment by wannabehacker007** [comment]
I have made four PRs in my forked repository of WiT, all of these contain the infographics that I had proposed to make earlier. Please merge them in the base repository's infographic branch.

**Comment by shikha-16** [comment]
@wannabehacker007 looks like you have created the PR in your own repo. I cannot merge it in this repo
Let me tell you the steps:
1. Fork this repo
2. Add your files to your forked repo
3. You will see something on top saying "this branch is ahead by x commits"
4. Click on the PR option there
6. Create a PR option from your forked repo to this original repo.
Then I will be able to see it

**Comment by wannabehacker007** [comment]
Hey, Shikha! Can you check out the PR that I made again?

**Pull request closed without merging**
